name: Test and release
on:
  push:
    branches:
      - master
      - 'hotfix-[0-9]+.[0-9]+**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
env:
  SBT_OPTS: "-XX:+CMSClassUnloadingEnabled -Xmx1G"
jobs:
  cleanup-previous-runs:
    name: Cleanup previous runs
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  tag-check:
    name: Tag Check
    runs-on: ubuntu-latest
    needs: [cleanup-previous-runs]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Unit test
        run: sbt -Dsbt.color=always -Dsbt.supershell=false checkTagExists
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [cleanup-previous-runs]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Unit test
        run: sbt -Dsbt.color=always -Dsbt.supershell=false clean test
  acceptance-test:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    needs: [cleanup-previous-runs]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Acceptance tests
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project acceptance-tests" clean test
  formatter:
    name: Formatter
    runs-on: ubuntu-latest
    needs: [cleanup-previous-runs]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Formatter
        run: sbt scalafmtCheck
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [tag-check, test, acceptance-test, formatter]
    if: "github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/hotfix-')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.RENKU_CI_TOKEN }}
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Create release
        run: |
          git config --global user.name "Renku Bot"
          git config --global user.email "renku@datascience.ch"
          sudo rm -rf .git/index.lock
          sbt "release default-tag-exists-answer k with-defaults"
